// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PrismApp.Player = (function(_super) {
  __extends(Player, _super);

  Player.prototype.texture = PIXI.Texture.fromImage("images/player_red.png");

  function Player(anchor, position) {
    Player.__super__.constructor.call(this, this.texture, anchor, position);
    this.velocity = 0;
    this.moveV = new PIXI.Point(0, 0);
    this.owner;
    this.position = 0;
    this.scale.x = 0.2 + Math.random() * 0.8;
    this.scale.y = this.scale.x;
    this.velocity = MAX_VEL / 20;
  }

  return Player;

})(PrismApp.Renderable);
