// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PrismApp.Player = (function(_super) {
  __extends(Player, _super);

  Player.prototype.texture = PIXI.Texture.fromImage("images/player_red.png");

  function Player(anchor, position) {
    Player.__super__.constructor.call(this, this.texture, anchor, position);
  }

  return Player;

})(PrismApp.Renderable);
