// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PrismApp.Renderable = (function(_super) {
  __extends(Renderable, _super);

  function Renderable(texture, anchor, position, velocity) {
    this.texture = texture;
    Renderable.__super__.constructor.call(this, this.texture);
    this.anchor.x = anchor.x;
    this.anchor.y = anchor.y;
    this.position.x = position.x;
    this.position.y = position.y;
    this.velocity = velocity;
    this.moveV = new PIXI.Point(0, 0);
  }

  Renderable.prototype.move = function() {
    this.moveV.x = this.velocity * Math.cos(this.rotation - Math.PI / 2);
    this.moveV.y = this.velocity * Math.sin(this.rotation - Math.PI / 2);
    this.position.x += moveV.x;
    return this.position.y += moveV.y;
  };

  return Renderable;

})(PIXI.Sprite);
